### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by asmasca** [iastro-pt/sBART#14]
Hi, I'm testing sBART today and I'm getting this error halfway trough the process. 

> TypeError: unsupported operand type(s) for /: 'str' and 'str'

It happens here: 

>setup_SBART_logger(
>   storage_path=storage_path / "logs",
>   RV_method=rv_method,
>   instrument=instrument,
>   log_to_terminal=True,
>)

and also in the function RV_routine.py at the line: 

>self._internalPaths.add_root_path(
>            storage_path / f"Iteration_{self.iteration_number}", self.storage_name
>       )

I'm fairly sure that if I manually change it to >> storage_path + f"Iteration_{self.iteration_number}" << it will work. The code is thinking that I'm trying to divide the strings, which obviously can't happen. 

In any case I don't really understand why it works for you but it doesn't for me. 

The full error is copied below: 
2022-05-13T13:26:19 - SBART.rv_calculation.rv_stepping.RV_step - CRITICAL - Found unknown error
Traceback (most recent call last):

>  File "sbart_extract.py", line 144, in <module>
>    rv_model.run_routine(data, storage_path, orders)
>    │        │           │     │             └ []
>    │        │           │     └ 'RESULTS/GJ526/DATA/SBART'
>    │        │           └ <AutoProxy[DataClass] object, typeid 'DataClass' at 0x7f0695ca9850>
>    │        └ <function RV_step.run_routine at 0x7f06906913a0>
>    └ <SBART.rv_calculation.rv_stepping.RV_step.RV_step object at 0x7f069077b250>
>
>> File "/usr/local/lib/python3.8/site-packages/sbart-0.1.0-py3.8-linux->x86_64.egg/SBART/rv_calculation/rv_stepping/RV_step.py", line 92, in run_routine
>    super().run_routine(
>  File "/usr/local/lib/python3.8/site-packages/sbart-0.1.0-py3.8-linux-x86_64.egg/SBART/Base_Models/RV_routine.py", line >260, in run_routine
>    storage_path / f"Iteration_{self.iteration_number}", self.storage_name
>    │                                                    │    └ <property object at 0x7f069e79af40>
>    │                                                    └ <SBART.rv_calculation.rv_stepping.RV_step.RV_step object at 0x7f069077b250>
>    └ 'RESULTS/GJ526/DATA/SBART'
>
>TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by Kamuish** [comment]
Hi @asmasca . Thanks for the feedback. It seems that a few incomplete features managed to creep in when I last pushed to this repository. I plan to fix them today, sorry about that

**Comment by asmasca** [comment]
Great, thank you. I changed it manually to be able to use it right now and I'll update when the new version is ready.

**Comment by Kamuish** [comment]
I wish you luck then. However, I am fairly certain that the actual s-BART approach is also down :(

**Comment by asmasca** [comment]
I managed to get RVs with the classical approach (haven't tried the Laplace yet). Although run to run behaviour seems a bit unstable. Sometimes it gets stuck when building the telluric model with Telfit. 

BTW Is there a way to make it ignore the CCF RV and provide an initial guess?

**Comment by Kamuish** [comment]
Could you define unstable? I haven't ran into any problems with TelFit. However, after the telluric template is created it should be always loaded from disk.

> BTW Is there a way to make it ignore the CCF RV and provide an initial guess? 

A user-provided initial guess is not supported for now, but it should be easy to do

**Comment by asmasca** [comment]
> Could you define unstable? I haven't ran into any problems with TelFit. However, after the telluric template is created it should 
> be always loaded from disk.

I've seen it sometimes get stuck after this line

2022-05-13T15:26:08 - SBART.template_creation.telluric_templates.telluric_from_telfit - INFO - Using params: [280.2, 750, 95.0, 385.34, 1819.0, 325.1]

Anyway, I found some other cases in which there are problems with joining strings, so I think I will just wait for the updates.

**Comment by Kamuish** [comment]
Hi @asmasca , 

This was more of a problem with the documentation than with the code. The RV routines were expecting a [pathlib](https://docs.python.org/3/library/pathlib.html) path, instead of a normal string. I have added support for "normal" strings, as well as pathlib objects


I will be closing this issue, as this will be fixed as soon as v 0.1.5 is released

**Comment by Kamuish** [comment]
@asmasca the new version (0.1.5) is now out.
