### ISSUE TITLE
Telfit hangs on

### ISSUE THREAD

**Issue by Kamuish** [iastro-pt/sBART#15]
> Could you define unstable? I haven't ran into any problems with TelFit. However, after the telluric template is created it should 
> be always loaded from disk.

I've seen it sometimes get stuck after this line

2022-05-13T15:26:08 - SBART.template_creation.telluric_templates.telluric_from_telfit - INFO - Using params: [280.2, 750, 95.0, 385.34, 1819.0, 325.1]

Anyway, I found some other cases in which there are problems with joining strings in other functions, so I think I will just wait for the updates.

_Originally posted by @asmasca in https://github.com/iastro-pt/sBART/issues/14#issuecomment-1126120223_

**Comment by Kamuish** [comment]
This might be related with the atmosphere profile download. To be checked

**Comment by asmasca** [comment]
Oh, I didn't know it was downloading the atmosphere profile! Then I think the problem was on my side. It was very likely the fault of the IAC VPN. It screws the connections with several services (with simbad and ESO for example). The inconsistency then is probably related to having the VPN on or off. 
 
I guess the only issue then is that it didn't notify a problem with the download.

**Comment by Kamuish** [comment]
To be honest, I am now fairly certain that it shouldn't be that.

In the logs you should see a line saying that the download managed to go through or that you managed to open the atmosphere profile from a (previously downloaded) profile list that is cached in your computer. You can find that lines relevant to the download near the following line (in the logs):

>  2022-05-13T19:59:10 - SBART.template_creation.telluric_templates.telluric_from_telfit - INFO - Launching GDAS profile downloader


However, if it passed this point, and you see nothing wrong before that line with the parameters, then it is all **telfit** doing its calculations.  Some small questions:

- Are you running every time on the same computer?  
- Does the computation eventually go through or is stuck there forever?


If the problem is telfit, I would suggesting trying to uninstall it and try to install it again using

```
pip install telfit  --no-cache-dir
```

to force a new download. Not sure that this will solve your problem of it being stuck
