### ISSUE TITLE
ERROR: Could not build wheels for SBART, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by DavidPiresG** [iastro-pt/sBART#34]
Hi Andre.

 I have been trying to install SBART but I get this error:

"ERROR: Could not build wheels for SBART, which is required to install pyproject.toml-based projects"

![image](https://github.com/iastro-pt/sBART/assets/153872140/93bd514e-641d-470e-8708-7d0802971d85)

I have tried with python 3.8.18 and python 3.9.18 in a ubuntu machine.

Thanks.

David

**Comment by Kamuish** [comment]
Hi David,
I have tried to install sbart on a clean environment and it works on my machine (both from pip and from a in-folder install). 

A few questions to understand what you are dealing with:
1) Which pip version are you using? Which setuptools version are you using?
2) Are you installing from pip or from a cloned version of the repository?

Cheers,
André

**Comment by DavidPiresG** [comment]
Thanks for your fast answer! I have created a clean enviroment after your answer.

1. The pip version is 23.3.1. I was using just 'pip install SBART'. Still not working.
2. After tried to install from the cloned version it works! So I have SBART working from now :)

Thanks! 

Regards, 
David.

**Comment by Kamuish** [comment]
Hi David,

I will look into the pip-version of s-BART, as it might not be reflecting some minor change on the repo..

Thanks,
André
