### ISSUE TITLE
ERROR: Could not build wheels for SBART which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by ThomasGWilson** [iastro-pt/sBART#8]
Hi Andre,

I've been trying to install S-BART using PIP and from the git repository, however I get the same error message when building the wheels and was wondering if you've encountered it before:

>>> ERROR: Could not build wheels for SBART which use PEP 517 and cannot be installed directly

After trying the fixes listed here (https://exerror.com/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installed-directly/), I get the following error:
>>> ERROR: Could not build wheels for SBART, which is required to install pyproject.toml-based projects

Which still seems to relate to PEP 517 and poetry, however i also get the "ModuleNotFoundError: No module named 'numpy'" error from the import numpy line in sbart build.py even though numpy is installed.

I on a Ubuntu 18.04 machine, using python 3.9.7 and pip 22.0.4.

Thanks,

Tom

**Comment by Kamuish** [comment]
Hi Tom, 

Thanks for the heads-up. I was missing a dependency on the build-requires. I am not sure why this was working fine for python3.8.... I will release a fixed version of SBART when I close this issue (which should be soon)

**Comment by Kamuish** [comment]
Hi Tom,

it should be fixed on the new version. Let me know if the install still fails.

Cheers,
André
